-- Database Name: data
CREATE DATABASE IF NOT EXISTS `data`;
USE `data`;

-- Users Table
CREATE TABLE IF NOT EXISTS `users` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `username` VARCHAR(100) UNIQUE NOT NULL,
    `password` VARCHAR(255) NOT NULL,
    `first_name` VARCHAR(50) NOT NULL,
    `middle_name` VARCHAR(50),
    `last_name` VARCHAR(50) NOT NULL,
    `role` ENUM('Admin', 'Evaluator', 'Proponent') NOT NULL,
    `position` ENUM('Research Coordinator', 'Extension Coordinator', 'College Dean', 'Head', 'Division Chief'), -- For Evaluators
    `college` ENUM('CEIT', 'CTHM', 'CITTE', 'CBA'), -- For Proponents/Evaluators
    `email` VARCHAR(150) UNIQUE NOT NULL,
    `is_blocked` TINYINT(1) DEFAULT 0,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Scholarly Works Table
CREATE TABLE IF NOT EXISTS `works` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `title` VARCHAR(255) NOT NULL,
    `quarter` ENUM('Q1', 'Q2', 'Q3', 'Q4') NOT NULL,
    `total_proposed_budget` INT NULL,
    `proposed_starting_date` DATE NULL,
    `proposed_completion_date` DATE NULL,
    `year` YEAR NOT NULL,
    `work_type` ENUM('Research', 'Extension') NOT NULL DEFAULT 'Research',
    `status` ENUM('Gray', 'Yellow', 'Red', 'Green') DEFAULT 'Gray',
    `current_step` ENUM('Research Coordinator', 'Extension Coordinator', 'College Dean', 'Head', 'Division Chief', 'Published') DEFAULT 'Research Coordinator',
    `created_by` INT NOT NULL,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (`created_by`) REFERENCES `users`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Work Authors (Multi-author support)
CREATE TABLE IF NOT EXISTS `work_authors` (
    `work_id` INT NOT NULL,
    `user_id` INT NOT NULL,
    `role` ENUM('leader','member') NOT NULL DEFAULT 'member',
    PRIMARY KEY (`work_id`, `user_id`),
    FOREIGN KEY (`work_id`) REFERENCES `works`(`id`) ON DELETE CASCADE,
    FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Work Files
CREATE TABLE IF NOT EXISTS `work_files` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `work_id` INT NOT NULL,
    `file_path` VARCHAR(255) NOT NULL,
    `file_name` VARCHAR(255) NOT NULL,
    `file_type` VARCHAR(50),
    `uploaded_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (`work_id`) REFERENCES `works`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Evaluations/Comments
CREATE TABLE IF NOT EXISTS `evaluations` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `work_id` INT NOT NULL,
    `evaluator_id` INT NOT NULL,
    `step` VARCHAR(100) NOT NULL,
    `status` ENUM('Red', 'Green') NOT NULL,
    `comment` TEXT NOT NULL,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (`work_id`) REFERENCES `works`(`id`) ON DELETE CASCADE,
    FOREIGN KEY (`evaluator_id`) REFERENCES `users`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Logs Table
CREATE TABLE IF NOT EXISTS `logs` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `user_id` INT,
    `action` VARCHAR(255) NOT NULL,
    `details` TEXT,
    `ip_address` VARCHAR(45),
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Profile Pictures Table
CREATE TABLE IF NOT EXISTS `profile_pictures` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `user_id` INT NOT NULL,
    `file_path` VARCHAR(255) NOT NULL,
    `status` ENUM('pending', 'approved', 'rejected') DEFAULT 'pending',
    `uploaded_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `reviewed_at` TIMESTAMP NULL,
    FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Insert initial Admin
-- Password: admin123 (hashed)
-- Password Hash for 'admin123' using BCRYPT: $2y$10$8.vVf6FpYpY8O7YpFmY0e.U4fB5JzK5jA8f5n/5mY/6mY/6mY/6mY
-- Wait, I'll use a real hash generated by password_hash('admin123', PASSWORD_BCRYPT)
-- Since I can't run PHP here easily to get a hash right now, I'll use a placeholder and update it shortly or use a known one.
-- Actually, I'll just write the SQL and let the user run it, or try to run it via mysql command if available.

INSERT INTO `users` (`username`, `password`, `first_name`, `last_name`, `role`, `email`) 
VALUES ('admin', '$2y$10$8v/tYx4Fm8f8f8f8f8f8f8f8f8f8f8f8f8f8f8f8f8f8f8f8', 'System', 'Admin', 'Admin', 'admin@csucc.edu.ph');
